SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
AUDIO_SUPPORTED = no

VIA_ENABLE = no
LTO_ENABLE = yes
ENCODER_MAP_ENABLE = no
CONSOLE_ENABLE = yes
KEYMAP_OVERLAY_ENABLE = yes

LAYER_LOCK_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no

RGB_MATRIX_ENABLE = no
RGB_MATRIX_SUPPORTED = no
RGBLIGHT_SUPPORTED = no

BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes

# Trackball
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3389 # Change to pmw3360 if you use that

# Encoder
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no

AUTO_SHIFT_ENABLE = no
